### ISSUE TITLE
Crate name unavailable on crates.io

### ISSUE THREAD

**Issue by a1akris** [a1akris/overwrite#2]
Hello, @a-kenji. I would like to publish this crate on crates.io, but it seems like you've reserved "overwrite" name. Do you need this reserve? If not, won't you mind to transfer ownership to me, please?

**Comment by a-kenji** [comment]
I have an unpublished prototype for this, but I am happy that you are taking this up.
My use case is exactly what this crate is doing now.

**Comment by a1akris** [comment]
Great, thank you. I will implement a proc macro to get rid of boilerplate trait implementations soon. Stay tuned :)
